### PR TITLE
Modernization PR

### PR DESCRIPTION
**Pull request by strega-nil**
Note, that this is not the full thing yet. I just wanted to upload it early to comment on some things.

### CODE REVIEW

**Comment by Gathros** [comment]
Are you done? @ubsan

**Comment by strega-nil** [comment]
Oh, yeah, sorry. Please comment up that function tho.

**Comment by Gathros** [comment]
What function?

**Comment by strega-nil** [comment]
bit-reverse-sort.

**Comment by Gathros** [comment]
Will do, Thanks.

**Pull request merged**
